<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="StateMachine" nsURI="se.studieren.mdd.transformer.StateMachine"
    nsPrefix="mdd">
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//Vertex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" upperBound="-1"
        eType="#//Region" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doActivity" eType="#//Behavior"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deferrableTrigger" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateInvariant" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="#//Behavior"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//Behavior"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isComposite" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSimple" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSubmachineState" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submachine" eType="#//StateMachine"
        eOpposite="#//StateMachine/submachineState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryPoint" eType="#//PseudoState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exitPoint" upperBound="-1"
        eType="#//PseudoState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vertex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/target"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subvertex" upperBound="-1"
        eType="#//Vertex" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoState" eSuperTypes="#//Vertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pseudoStateKind" eType="#//PseudoStateKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        upperBound="-1" eType="#//Region" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submachineState" upperBound="-1"
        eType="#//State" eOpposite="#//State/submachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Vertex" eOpposite="#//Vertex/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Vertex" eOpposite="#//Vertex/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effect" eType="#//Behavior"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//TransitionKind"
        defaultValueLiteral="external"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitionKind">
    <eLiterals name="internal"/>
    <eLiterals name="local" value="1"/>
    <eLiterals name="external" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PseudoStateKind">
    <eLiterals name="initial"/>
    <eLiterals name="join" value="1"/>
    <eLiterals name="fork" value="2"/>
    <eLiterals name="junction" value="3"/>
    <eLiterals name="choice" value="4"/>
    <eLiterals name="entryPoint" value="5"/>
    <eLiterals name="exitPoint" value="6"/>
    <eLiterals name="terminate" value="7"/>
    <eLiterals name="deepHistory" value="8"/>
    <eLiterals name="shallowHistory" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeBlock" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
</ecore:EPackage>
