<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BehaviourTable" nsURI="se.studieren.mdd.transformer.Behaviour"
    nsPrefix="mdd">
  <eClassifiers xsi:type="ecore:EClass" name="Behaviour">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
        eType="#//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preState" lowerBound="1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postState" lowerBound="1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inmessage" lowerBound="1"
        eType="#//InMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activation" lowerBound="1"
        eType="#//Activation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outmessages" upperBound="-1"
        eType="#//OutMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" lowerBound="1"
        eType="#//Return" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="#//Object" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" lowerBound="1"
        eType="#//Return" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Return" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Return">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemObject" eSuperTypes="#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
