<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ScenarioTable" nsURI="se.studieren.mdd.transformer.ScenarioTable"
    nsPrefix="mdd">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="communication" lowerBound="1"
        upperBound="-1" eType="#//Communication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communication" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserCommunication" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usermessage" lowerBound="1"
        eType="#//UserMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returned" lowerBound="1"
        eType="#//ReturnValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemCommunication" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returned" lowerBound="1"
        eType="#//ReturnValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemmessage" lowerBound="1"
        eType="#//SystemMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prestate" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="poststate" lowerBound="1"
        eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserMessage" eSuperTypes="#//Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
        eType="#//ActorObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemMessage" eSuperTypes="#//Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
        eType="#//ActorObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="#//SystemObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//ReturnValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="VoidValue" eSuperTypes="#//ReturnValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActorObject" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemObject" eSuperTypes="#//ActorObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//ActorObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="State"/>
</ecore:EPackage>
