<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ScenarioTable" nsURI="se.studieren.mdd.transformer.ScenarioTable"
    nsPrefix="mdd">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="communication" lowerBound="1"
        upperBound="-1" eType="#//Communication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communication" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserCommunication" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usermessage" lowerBound="1"
        eType="#//UserMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" lowerBound="1"
        eType="#//Return"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemCommunication" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="2" upperBound="2"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" lowerBound="1"
        eType="#//Return"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemmessage" lowerBound="1"
        eType="#//SystemMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserMessage" eSuperTypes="#//Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemMessage" eSuperTypes="#//Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemobject" lowerBound="1"
        eType="#//SystemObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Return" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Return"/>
  <eClassifiers xsi:type="ecore:EClass" name="void" eSuperTypes="#//Return"/>
  <eClassifiers xsi:type="ecore:EClass" name="Object" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemObject" eSuperTypes="#//Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
</ecore:EPackage>
