<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IOAutomaton" nsURI="se.studieren.mdd.transformer.IOAutomaton"
    nsPrefix="mdd">
  <eClassifiers xsi:type="ecore:EClass" name="Vertex" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//Vertex"/>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//Vertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Vertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inmessage" eType="#//InMessage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outmessage" upperBound="-1"
        eType="#//OutMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnvalue" eType="#//ReturnValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Vertex"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="VoidValue" eSuperTypes="#//ReturnValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//ReturnValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InMessage" eSuperTypes="#//Message"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutMessage" eSuperTypes="#//Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actorobject" lowerBound="1"
        eType="#//ActorObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnvalue" lowerBound="1"
        eType="#//ReturnValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorObject" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//ActorObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemObject" eSuperTypes="#//ActorObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOAutomaton">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertex" lowerBound="2"
        upperBound="-1" eType="#//Vertex" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="1"
        upperBound="-1" eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemobject" lowerBound="1"
        eType="#//SystemObject" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
