<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="InteractionDiagram" nsURI="se.studieren.mdd.transformer.InteractionDiagram"
    nsPrefix="mdd">
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionOperatorKind">
    <eLiterals name="seq"/>
    <eLiterals name="alt" value="1"/>
    <eLiterals name="opt" value="2"/>
    <eLiterals name="break" value="3"/>
    <eLiterals name="par" value="4"/>
    <eLiterals name="strict" value="5"/>
    <eLiterals name="loop" value="6"/>
    <eLiterals name="critical" value="7"/>
    <eLiterals name="neg" value="8"/>
    <eLiterals name="assert" value="9"/>
    <eLiterals name="ignore" value="10"/>
    <eLiterals name="consider" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageOccurenceSpecification" eSuperTypes="#//MessageEnd #//OccurrenceSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageEnd" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendEvent" eType="#//MessageEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveEvent" eType="#//MessageEnd"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageSort" eType="#//MessageSort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction" eSuperTypes="#//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifeline" upperBound="-1"
        eType="#//Lifeline" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragment" upperBound="-1"
        eType="#//InteractionFragment" containment="true" eOpposite="#//InteractionFragment/enclosingInteraction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coveredBy" upperBound="-1"
        eType="#//InteractionFragment" eOpposite="#//InteractionFragment/covered"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFragment" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingInteraction" eType="#//Interaction"
        eOpposite="#//Interaction/fragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="covered" lowerBound="1"
        eType="#//Lifeline" eOpposite="#//Lifeline/coveredBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalordering" upperBound="-1"
        eType="#//GeneralOrdering" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccurrenceSpecification" eSuperTypes="#//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toAfter" upperBound="-1"
        eType="#//GeneralOrdering" eOpposite="#//GeneralOrdering/before"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toBefore" upperBound="-1"
        eType="#//GeneralOrdering" eOpposite="#//GeneralOrdering/after"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedFragment" eSuperTypes="#//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interactionOperator" eType="#//InteractionOperatorKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        upperBound="-1" eType="#//InteractionOperand" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionOperand" eSuperTypes="#//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragment" upperBound="-1"
        eType="#//InteractionFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateInvariant" eSuperTypes="#//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invariant" lowerBound="1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageSort">
    <eLiterals name="synchCall"/>
    <eLiterals name="asynchCall" value="1"/>
    <eLiterals name="asynchSignal" value="2"/>
    <eLiterals name="createMessage" value="3"/>
    <eLiterals name="deleteMessage" value="4"/>
    <eLiterals name="reply" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionOccurenceSpecification" eSuperTypes="#//OccurrenceSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="execution" lowerBound="1"
        eType="#//ExecutionSpecification" eOpposite="#//ExecutionSpecification/executionOccurenceSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorExecutionSpecification" eSuperTypes="#//ExecutionSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//OccurrenceSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finish" lowerBound="1"
        eType="#//OccurrenceSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionSpecification" eSuperTypes="#//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionOccurenceSpecification"
        upperBound="2" eType="#//ExecutionOccurenceSpecification" eOpposite="#//ExecutionOccurenceSpecification/execution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralOrdering">
    <eStructuralFeatures xsi:type="ecore:EReference" name="before" lowerBound="1"
        eType="#//OccurrenceSpecification" eOpposite="#//OccurrenceSpecification/toAfter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="after" lowerBound="1" eType="#//OccurrenceSpecification"
        eOpposite="#//OccurrenceSpecification/toBefore"/>
  </eClassifiers>
</ecore:EPackage>
